### ISSUE TITLE
Icons have a small offset

### ISSUE THREAD

**Issue by Zazo032** [bigbadbob2003/flutter_tabler_icons#3]
When using an icon inside a `CircleAvatar`, `TablerIcons` have a small undesired offset compared to Material Design ones.

```dart
CircleAvatar(
  child: Icon(
    Icons.check,
    size: 24.0,
  ),
),
```
vs
```dart
CircleAvatar(
  child: Icon(
    TablerIcons.check,
    size: 24.0,
  ),
),
```

**Comment by bigbadbob2003** [comment]
There is currently an open issue on the tabler-icons repository regarding this https://github.com/tabler/tabler-icons/issues/118 ideally it needs to be fixed there as any change here would have to be reverted in the future

**Comment by bawantha** [comment]
This is true,

**Comment by bigbadbob2003** [comment]
This might be fixed it the latest version using tabler icons 2.23.0

**Comment by Chaphasilor** [comment]
Can confirm that the issue has been fixed :)

**Comment by Xoshbin** [comment]
I'm on the latest version, but the issue still persists.

**Comment by Chaphasilor** [comment]
Are you sure Flutter properly upgraded the package? And are all icons affected or only some?

**Comment by Xoshbin** [comment]
@Chaphasilor Sorry I wasn't expecting that fast reply, yes I just did a flutter clean, and all the Icons I'm using are affected like TablerIcons.arrow_big_up , TablerIcons.share .

I have to add padding to align it:

```
    Padding(
        padding: const EdgeInsets.only(bottom: 4.0),
        child: Icon(
             TablerIcons.arrow_big_up
        ),
    )
```

**Comment by Chaphasilor** [comment]
Hmm, I'm not the dev but maybe I can check later if I can reproduce the issue...

**Comment by bigbadbob2003** [comment]
i can confirm there is an offset on those icons you mentioned.

However i just use the font file provided by Tabler icons so you will need to raise an issue there to get the TTF fixed https://github.com/tabler/tabler-icons

![image](https://github.com/bigbadbob2003/flutter_tabler_icons/assets/47393191/43031404-9278-43a2-8d48-84a6fab09fc8)
